
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 # Definida por padrão
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ice_cream_db
  
test:
  <<: *default
  database: icecream_api_test


production:
  <<: *default
  database: icecream_api_production
  username: icecream_api
  password: <%= ENV["ICECREAM_API_DATABASE_PASSWORD"] %>
